# Generated by Django 5.2 on 2025-04-10 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('mood', models.CharField(choices=[('H', [('label', 'Happy'), ('emoji', '😊'), ('color', '#FFD93D')]), ('S', [('label', 'Sad'), ('emoji', '😢'), ('color', '#3A86FF')]), ('A', [('label', 'Angry'), ('emoji', '😠'), ('color', '#FF595E')]), ('N', [('label', 'Neutral'), ('emoji', '😐'), ('color', '#A0A0A0')]), ('G', [('label', 'Grateful'), ('emoji', '🙏'), ('color', '#FFCA3A')]), ('C', [('label', 'Content'), ('emoji', '🧘'), ('color', '#70D6FF')]), ('E', [('label', 'Excited'), ('emoji', '🤩'), ('color', '#FF9F1C')]), ('T', [('label', 'Tired'), ('emoji', '😴'), ('color', '#BDB2FF')]), ('O', [('label', 'Overwhelmed'), ('emoji', '😵'), ('color', '#7209B7')]), ('R', [('label', 'Reflective'), ('emoji', '🤔'), ('color', '#80ED99')]), ('B', [('label', 'Bored'), ('emoji', '😐'), ('color', '#D3D3D3')]), ('M', [('label', 'Motivated'), ('emoji', '💪'), ('color', '#06D6A0')])], default='C')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
