# Generated by Django 5.2 on 2025-04-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mood',
            field=models.CharField(choices=[('M', 'Motivated'), ('H', 'Happy'), ('S', 'Sad'), ('A', 'Angry'), ('N', 'Neutral'), ('G', 'Grateful'), ('C', 'Content'), ('E', 'Excited'), ('T', 'Tired'), ('O', 'Overwhelmed'), ('R', 'Reflective'), ('B', 'Bored')], default='C', max_length=1),
        ),
    ]
