# Generated by Django 5.2 on 2025-04-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(verbose_name='Comment'),
        ),
    ]
